name: tgdb

services:
  tgdb:
    image: tgdb:dev
    container_name: tgdb
    build:
      context: ../../
      dockerfile: deploy/dev/tgdb/Dockerfile
      tags:
        - "tgdb:dev"
    volumes:
      - ../..:/app
      - tgdb-data:/run/app
    environment:
      CONF_PATH: /app/deploy/dev/tgdb/conf.yaml
    ports:
      - 8000:8000
    command: tgdb-dev

volumes:
  tgdb-data: null
