name: tgdb

services:
  tgdb:
    image: tgdb:dev
    container_name: tgdb
    build:
      context: ../../
      dockerfile: deployments/dev/tgdb/Dockerfile
      tags:
        - "tgdb:dev"
    volumes:
      - ../..:/app
      - tgdb-data:/run/app
    command: bash

volumes:
  tgdb-data: null
